services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - rag_docs_data:/var/lib/postgresql

  chroma:
    image: chromadb/chroma
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - rag_docs_data:/data/chromadb

  migrator:
    build:
      context: .
      dockerfile: docker/DockerFile.migrator
      cache_from:
        - rag_backend:latest
    container_name: rag_migrator
    env_file:
      - ./apps/backend/.env
    depends_on:
      db:
        condition: service_started
    restart: "no"

  rag_backend:
    build:
      context: .
      dockerfile: docker/DockerFile.backend
      cache_from:
        - rag_backend:latest
    container_name: rag_backend
    ports:
      - "8080:8080"
    env_file:
      - ./apps/backend/.env
    depends_on:
      migrator:
        condition: service_completed_successfully
      chroma:
        condition: service_started

  # web:
  #   build:
  #     context: .
  #     dockerfile: docker/DockerFile.frontend
  #   container_name: web
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ./apps/web/.env
  #   depends_on:
  #     - rag_backend

volumes:
  rag_docs_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/reek/.docker/volumes/rag_docs_data
