FROM oven/bun:1-slim AS build

WORKDIR /build

COPY ./bun.lock ./package.json ./
COPY ./apps/web/package.json ./apps/web/package.json
COPY ./packages/eslint-config/package.json ./packages/eslint-config/package.json
COPY ./packages/typescript-config/package.json ./packages/typescript-config/package.json
COPY ./packages/ui/package.json ./packages/ui/package.json

RUN bun install --frozen-lockfile

COPY ./apps/web/ ./apps/web/

WORKDIR /build/apps/web
RUN bun run build

FROM oven/bun:1-slim

WORKDIR /app/apps/web

ENV NODE_ENV=production

COPY --from=build /build/apps/web/package.json ./package.json
COPY --from=build /build/apps/web/.next ./.next
COPY --from=build /build/apps/web/public ./public
COPY --from=build /build/apps/web/next.config.ts ./next.config.ts
COPY --from=build /build/node_modules /app/node_modules

EXPOSE 3000

CMD ["bun", "run", "start"]