FROM python:3.12-slim AS builder

WORKDIR /build

RUN pip install --no-cache-dir --root-user-action=ignore uv

COPY ./apps/backend/.python-version ./apps/backend/pyproject.toml ./apps/backend/uv.lock ./

ENV VIRTUAL_ENV=/build/.venv
RUN uv venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN UV_INDEX_URL=https://pypi.org/simple \
    UV_NO_CACHE=1 \
    uv sync --frozen

FROM python:3.12-slim

WORKDIR /apps

COPY --from=builder /build/.venv /build/.venv
COPY ./apps/backend/app ./app

ENV VIRTUAL_ENV=/build/.venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

EXPOSE 8080

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
