"""updated chat table session id

Revision ID: e4e1bac32957
Revises: e1e855eaf319
Create Date: 2026-01-07 19:46:00.091414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4e1bac32957'
down_revision: Union[str, Sequence[str], None] = 'e1e855eaf319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the old foreign key constraint first
    op.drop_constraint(op.f('chats_session_id_fkey'), 'chats', type_='foreignkey')
    # Then alter the column type
    op.alter_column('chats', 'session_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    # Finally create the new foreign key
    op.create_foreign_key(None, 'chats', 'sessions', ['session_id'], ['session_token'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key(op.f('chats_session_id_fkey'), 'chats', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.alter_column('chats', 'session_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
